# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee20c93a2f8d8a70926f6bb248df0af98b0de8d0a41dcab5f9901aec17f57a94c7261e2adbfe702c8d3031afe33f73bdf67853153be58f21f274e32469967aae

test:
  secret_key_base: eb304e39cefd0fc95b91303215cd30e2ee1795c525ac9f1d019729a84fea12623f3d46d898d5a5879fe1e06f7e0b5174b00cec26753de4d014e246179675ee9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
